name: le5le-topology
version: 0.0.1
cpu: 1
port: 8200
jwt: IKJfd345shJhdf
secret: le5le-HJdfhs
mongo:
  address: 127.0.0.1:27017
  database: le5leTopology
  #user: xxxx
  #password: xxxx
  maxConnections: 10
  Timeout: 30
  logLevel: 1
  mechanism: SCRAM-SHA-1
  debug: false
redis:
  maxConnections: 10
  address: 127.0.0.1:6379
  #password: xxxx
  Timeout: 30
  database: 1
log:
  #filename: filename
  maxSize: 300
  maxBackups: 5
  maxAge: 30
